openapi: 3.0.1
info:
  title: MockAPIArl
  description: API Definition of MockAPIArl
  version: 1.0.0
servers:
- url: http://localhost:8290/mockarl
paths:
  /:
    get:
      responses:
        default:
          description: Default response
