openapi: 3.0.1
info:
  title: MockARL
  description: API Definition of MockARL
  version: 1.0.0
servers:
- url: http://localhost:8290/mockarl
paths:
  /:
    get:
      responses:
        default:
          description: Default response
